name 'infra_hardening'
maintainer 'Yvo van Doorn'
maintainer_email 'yvo@chef.io'
license 'all_rights'
description 'Installs/Configures infra_hardening'
issues_url 'https://github.com/chef-cft/infra_hardening/issues'
source_url 'https://github.com/chef-cft/infra_hardening'
long_description 'Installs/Configures infra_hardening'
version '0.7.0'
